# Generated by Django 4.2.7 on 2024-07-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictOfficeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_headoffice', 'Can view head office website'), ('view_districtoffice', 'Can view district office website'), ('view_branchlocation', 'Can view branch location website')]},
        ),
        migrations.CreateModel(
            name='OfficeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('districtofficelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.districtofficelist')),
            ],
        ),
    ]
