# Generated by Django 4.2.7 on 2024-07-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_districtofficelist_alter_user_options_officename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officename',
            name='complete',
        ),
    ]
