# Generated by Django 4.2.14 on 2024-07-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_officename_complete"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OfficeName",
            new_name="BranchLocation",
        ),
    ]
